Porting AutoPowerMeasurement code from Eclipse to AndroidStudio
Need to add the action#name to intent-filter in AndroidManifest.xml
===================================================
Error: Missing one of the key attributes 'action#name,category#name' on
element intent-filter at AndroidManifest.xml
===================================================